using System.Reflection;
using System.Reflection.Emit;

namespace SpaceBattle.Lib;

public static class AdapterGenerator
{
    // Динамическая сборка, в которую помещаются все сгенерированные типы
    private static readonly AssemblyBuilder _assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(
            new AssemblyName("SpaceBattle.AutoGenerated"),
            AssemblyBuilderAccess.Run);

    // Модуль внутри сборки — контейнер для типов
    private static readonly ModuleBuilder _moduleBuilder =  _assemblyBuilder.DefineDynamicModule("MainModule");

    // Генерирует тип-адаптер для переданного интерфейса
    public static Type Generate(Type interfaceType)
    {
        var typeName = $"AutoGenerated.{interfaceType.Name}Adapter";

        // Определяем новый публичный класс, реализующий interfaceType
        var typeBuilder = _moduleBuilder.DefineType(
            typeName,
            TypeAttributes.Public | TypeAttributes.Class,
            typeof(object),
            new[] { interfaceType }
        );

        var objField = typeBuilder.DefineField("_obj", typeof(object), FieldAttributes.Private);

        // Конструктор принимает object, сохраняет в _obj
        var ctor = typeBuilder.DefineConstructor(
            MethodAttributes.Public,
            CallingConventions.Standard,
            new[] { typeof(object) }
        );
        var ctorIl = ctor.GetILGenerator();
        ctorIl.Emit(OpCodes.Ldarg_0);
        ctorIl.Emit(OpCodes.Call, typeof(object).GetConstructor(Type.EmptyTypes)!);
        ctorIl.Emit(OpCodes.Ldarg_0);
        ctorIl.Emit(OpCodes.Ldarg_1);
        ctorIl.Emit(OpCodes.Stfld, objField);
        ctorIl.Emit(OpCodes.Ret);

        // Генерируем реализацию каждого метода интерфейса
        foreach (var method in interfaceType.GetMethods())
        {
            GenerateMethod(typeBuilder, objField, interfaceType, method);
        }

        return typeBuilder.CreateType()!;
    }

    // Генерирует один метод адаптера (void или с возвращаемым значением)
    private static void GenerateMethod(
        TypeBuilder typeBuilder,
        FieldInfo objField,
        Type interfaceType,
        MethodInfo method)
    {
        var parameters = method.GetParameters();
        var paramTypes = parameters.Select(p => p.ParameterType).ToArray();

        var methodBuilder = typeBuilder.DefineMethod(
            method.Name,
            MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.Final,
            method.ReturnType,
            paramTypes
        );

        var il = methodBuilder.GetILGenerator();
        var iocKey = BuildIoCKey(interfaceType, method);

        if (method.ReturnType == typeof(void))
        {
            // void-метод: IoC.Resolve<ICommand>(key, obj, args...).Execute()
            GenerateVoidMethod(il, objField, iocKey, paramTypes);
        }
        else
        {
            // метод с возвращаемым значением: return IoC.Resolve<T>(key, obj)
            GenerateGetMethod(il, objField, iocKey, method.ReturnType);
        }

        typeBuilder.DefineMethodOverride(methodBuilder, method);
    }

    // IL для void-метода: собирает массив аргументов, резолвит ICommand, вызывает Execute
    private static void GenerateVoidMethod(
        ILGenerator il,
        FieldInfo objField,
        string iocKey,
        Type[] paramTypes)
    {
        // object[] args = new object[paramTypes.Length + 1]
        var argsLocal = il.DeclareLocal(typeof(object[]));
        il.Emit(OpCodes.Ldc_I4, paramTypes.Length + 1);
        il.Emit(OpCodes.Newarr, typeof(object));
        il.Emit(OpCodes.Stloc, argsLocal);

        // args[0] = _obj
        il.Emit(OpCodes.Ldloc, argsLocal);
        il.Emit(OpCodes.Ldc_I4_0);
        il.Emit(OpCodes.Ldarg_0);
        il.Emit(OpCodes.Ldfld, objField);
        il.Emit(OpCodes.Stelem_Ref);

        // args[i+1] = параметр метода (боксируем value types)
        for (int i = 0; i < paramTypes.Length; i++)
        {
            il.Emit(OpCodes.Ldloc, argsLocal);
            il.Emit(OpCodes.Ldc_I4, i + 1);
            il.Emit(OpCodes.Ldarg, i + 1);
            if (paramTypes[i].IsValueType)
                il.Emit(OpCodes.Box, paramTypes[i]);
            il.Emit(OpCodes.Stelem_Ref);
        }

        // IoC.Resolve<ICommand>(key, args).Execute()
        il.Emit(OpCodes.Ldstr, iocKey);
        il.Emit(OpCodes.Ldloc, argsLocal);
        var resolveMethod = typeof(IoC)
            .GetMethod("Resolve")!
            .MakeGenericMethod(typeof(ICommand));
        il.Emit(OpCodes.Call, resolveMethod);
        il.Emit(OpCodes.Callvirt, typeof(ICommand).GetMethod("Execute")!);
        il.Emit(OpCodes.Ret);
    }

    // IL для get-метода: резолвит значение через IoC и возвращает его
    private static void GenerateGetMethod(
        ILGenerator il,
        FieldInfo objField,
        string iocKey,
        Type returnType)
    {
        // object[] args = new object[1] { _obj }
        var argsLocal = il.DeclareLocal(typeof(object[]));
        il.Emit(OpCodes.Ldc_I4_1);
        il.Emit(OpCodes.Newarr, typeof(object));
        il.Emit(OpCodes.Stloc, argsLocal);

        il.Emit(OpCodes.Ldloc, argsLocal);
        il.Emit(OpCodes.Ldc_I4_0);
        il.Emit(OpCodes.Ldarg_0);
        il.Emit(OpCodes.Ldfld, objField);
        il.Emit(OpCodes.Stelem_Ref);

        // return IoC.Resolve<returnType>(key, args)
        il.Emit(OpCodes.Ldstr, iocKey);
        il.Emit(OpCodes.Ldloc, argsLocal);
        var resolveMethod = typeof(IoC)
            .GetMethod("Resolve")!
            .MakeGenericMethod(returnType);
        il.Emit(OpCodes.Call, resolveMethod);
        il.Emit(OpCodes.Ret);
    }

    // Строит ключ IoC по соглашению:
    // GetXxx -> "InterfaceName:xxx.get"
    // SetXxx -> "InterfaceName:xxx.set"
    // name   -> "InterfaceName:methodname"
    private static string BuildIoCKey(Type interfaceType, MethodInfo method)
    {
        var name = method.Name;
        var ifaceName = interfaceType.FullName ?? interfaceType.Name;

        if (name.StartsWith("Get", StringComparison.OrdinalIgnoreCase))
        {
            var prop = name[3..].ToLower();
            return $"{ifaceName}:{prop}.get";
        }

        if (name.StartsWith("Set", StringComparison.OrdinalIgnoreCase))
        {
            var prop = name[3..].ToLower();
            return $"{ifaceName}:{prop}.set";
        }

        return $"{ifaceName}:{name.ToLower()}";
    }
}